"""Z-learning: data-driven RL for infinite-horizon KL control (Section 7.3.3).

Like Q-learning, Z-learning allows the estimate Z_hat of the desirability
function to be updated using data (physical or simulated) that becomes
available in each time step.

Let x_t, u_t, x_{t+1} be the transition generated by the reference policy
and C_t = C(x_t, u_t) the observed cost. The estimate is updated as:

  Z_hat(x_t) <- (1 - theta) Z_hat(x_t) + theta exp(-C_t/alpha) Z_hat(x_{t+1})

where theta_t is a diminishing learning rate.                            (Eq. 7.82)
"""

import numpy as np


def z_learning(grid, alpha, goal_state, n_episodes, max_steps, rng,
               warmup=10):
    """Z-learning via online updates (Eq. 7.82).

    Uses per-state visit counts for the learning rate:
    theta_t(x) = warmup / (warmup + N_t(x)).

    Parameters
    ----------
    grid : GridWorld
    alpha : float
    goal_state : int
    n_episodes : int
    max_steps : int
        Maximum steps per episode.
    rng : numpy.random.Generator
    warmup : int
        Learning rate warmup constant. Larger values keep the
        learning rate higher for longer.

    Returns
    -------
    Z : array of shape (n_states,)
    history : list of Z snapshots (one per episode)
    """
    n = grid.n_states
    Z = np.ones(n)
    Z[goal_state] = 1.0
    visit_counts = np.zeros(n)
    history = [Z.copy()]

    valid_starts = [s for s in range(n)
                    if s != goal_state
                    and grid.state_to_rc(s) not in grid.obstacles]

    # ##########################################################
    # TODO: Implement Z-learning (Eq. 7.82). For each episode,
    # start from a random valid state and follow the reference
    # policy. At each step, observe the transition (x_t, u_t,
    # x_{t+1}) and cost C_t = C(x_t, u_t), then update:
    #
    #   Z(x_t) <- (1-theta) Z(x_t) + theta exp(-C_t/alpha) Z(x_{t+1})
    #
    # Use per-state visit counts for the learning rate:
    #   theta(x) = warmup / (warmup + N(x))
    # Pin Z(goal) = 1 after each episode.
    # Append Z.copy() to history after each episode.
    #
    # ##########################################################
    raise NotImplementedError("TODO: z_learning")

    return Z, history
